Practical change to Copy failures
This scenario is quite common. Trying to copy files from S3 to a case-insensitive file system (OSX):

```
Traceback (most recent call last):
  File "/Users/me/env/bin/s3cmd", line 2805, in <module>
    rc = main()
  File "/Users/me/env/bin/s3cmd", line 2713, in main
    rc = cmd_func(args)
  File "/Users/me/env/bin/s3cmd", line 1668, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/Users/me/env/bin/s3cmd", line 1315, in cmd_sync_remote2local
    failed_copy_list = local_copy(copy_pairs, destination_base)
  File "/Users/me/env/bin/s3cmd", line 1349, in local_copy
    shutil.copy2(deunicodise(src_file), deunicodise(dst_file))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `./File` and `./file` are the same file
```